#!/bin/sh

tmp=`tempfile`

mountpoint="/home/koti/KiKaData/"

loc="$1"
defloc="Salmisaari"
ask=0

if [ "x$loc" = "x" ]; then
	loc=$defloc
	ask=1
fi

rsync -rv --update "$mountpoint" data | fgrep -i .csv > $tmp

cd data

if [ -s $tmp ]; then

	n=`wc -l < $tmp`
	echo "Found $n new ascent files"

	while read -r fname
	do	
		f="$fname"

		if [ "$ask" -eq 1 ]; then
			echo
			head -1 $f | fmt
			echo -n "Location of $fname (ENTER=$loc, !=Set all to $loc)? "
			read newloc < /dev/tty
			if [ "x$newloc" = "x!" ]; then
				ask=0
				newloc=$loc # restore old value
			fi
			if [ ! "x$newloc" = "x" ]; then
				loc=$newloc
			fi
		fi
		
		../setloc -loc "$loc" $f
		
	done < $tmp
	
	../adastra -v `cat $tmp`
fi

rm -f $tmp


